export interface Product {
  id: string;
  name: string;
  composition: string;
  category: string;
  therapeuticSegment: string;
  dosageForm: string;
  strength?: string;
  packSize?: string;
  image?: string;
  description?: string;
  featured?: boolean;
  active?: boolean;
}

export const PRODUCT_CATEGORIES = [
  'Pain Management',
  'Anti-inflammatory',
  'Bone & Nutritional Health',
  'Digestive Health',
  'Neuro / Vitamin Support',
  'Anti-infective',
  'Cough & Cold',
  'Anti-allergic',
  'Prescription / Specialty Products',
  'Topical Products',
];

export const DOSAGE_FORMS = [
  'Tablet',
  'Capsule',
  'Injection',
  'Dry Syrup',
  'Oil',
  'Suspension',
  'Solution',
];

export const initialProducts: Product[] = [
  {
    id: 'acevar-p',
    name: 'ACEVAR-P',
    composition: 'Aceclofenac 100 mg + Paracetamol 325 mg',
    category: 'Pain Management',
    therapeuticSegment: 'Anti-inflammatory',
    dosageForm: 'Tablet',
    packSize: 'Strip of 10',
    description: 'Combination analgesic and anti-inflammatory formulation for effective pain relief.',
    featured: true,
    active: true,
  },
  {
    id: 'acevar-sp',
    name: 'ACEVAR-SP',
    composition: 'Aceclofenac 100 mg + Paracetamol 325 mg + Serratiopeptidase 15 mg',
    category: 'Pain Management',
    therapeuticSegment: 'Anti-inflammatory',
    dosageForm: 'Tablet',
    packSize: 'Strip of 10',
    description: 'Enhanced formulation with serratiopeptidase for additional anti-inflammatory benefits.',
    featured: true,
    active: true,
  },
  {
    id: 'acevar-et',
    name: 'ACEVAR-ET',
    composition: 'Etoricoxib 60 mg + Paracetamol 325 mg',
    category: 'Pain Management',
    therapeuticSegment: 'Anti-inflammatory',
    dosageForm: 'Tablet',
    packSize: 'Strip of 10',
    description: 'Selective COX-2 inhibitor combined with paracetamol for superior pain management.',
    featured: false,
    active: true,
  },
  {
    id: 'acevar-tc',
    name: 'ACEVAR-TC',
    composition: 'Aceclofenac 100 mg + Paracetamol 325 mg + Trypsin Chymotrypsin 150000 AU',
    category: 'Pain Management',
    therapeuticSegment: 'Anti-inflammatory',
    dosageForm: 'Tablet',
    packSize: 'Strip of 10',
    description: 'Triple action formulation with enzymatic proteolytic activity for enhanced therapeutic benefit.',
    featured: false,
    active: true,
  },
  {
    id: 'arthowex-oil',
    name: 'ARTHOWEX OIL',
    composition: 'Proprietary herbal formulation',
    category: 'Pain Relief',
    therapeuticSegment: 'Topical Products',
    dosageForm: 'Oil',
    packSize: '100 ml',
    description: 'Premium topical pain relief oil for localized application.',
    featured: false,
    active: true,
  },
  {
    id: 'lycovarex-plus',
    name: 'LYCOVAREX PLUS',
    composition: 'Calcium Citrate Malate + Magnesium Hydroxide + Zinc Sulphate Monohydrate + Vitamin D3 + Methylcobalamin + L-Methylfolate + Pyridoxal-5-Phosphate',
    category: 'Bone & Nutritional Health',
    therapeuticSegment: 'Nutritional Supplement',
    dosageForm: 'Tablet',
    packSize: 'Strip of 15',
    description: 'Comprehensive bone and nutritional support with essential minerals and vitamins.',
    featured: true,
    active: true,
  },
  {
    id: 'lycovarex-forte',
    name: 'LYCOVAREX FORTE',
    composition: 'Lycopene + Antioxidant Complex + Vitamins',
    category: 'Bone & Nutritional Health',
    therapeuticSegment: 'Antioxidants / Multivitamins',
    dosageForm: 'Tablet',
    packSize: 'Strip of 15',
    description: 'Potent antioxidant formulation for overall health and wellness.',
    featured: false,
    active: true,
  },
  {
    id: 'lycovarex-max',
    name: 'LYCOVAREX MAX',
    composition: 'Cissus Quadrangularis + Calcium Citrate + Vitamin D',
    category: 'Bone & Nutritional Health',
    therapeuticSegment: 'Bone Health',
    dosageForm: 'Tablet',
    packSize: 'Strip of 15',
    description: 'Maximum strength bone health support with natural ingredients.',
    featured: false,
    active: true,
  },
  {
    id: 'myncobal-gold',
    name: 'MYNCOBAL GOLD',
    composition: 'Methylcobalamin + Nicotinamide + Pyridoxine HCl',
    category: 'Neuro / Vitamin Support',
    therapeuticSegment: 'Vitamin B12 Support',
    dosageForm: 'Injection',
    strength: '500 mcg/ml or 1000 mcg/ml',
    packSize: 'Vial of 1 ml',
    description: 'Premium B-complex formulation for neurological health and energy metabolism.',
    featured: true,
    active: true,
  },
  {
    id: 'ravarzol-dsr',
    name: 'RAVARZOL-DSR',
    composition: 'Rabeprazole Sodium 20 mg + Domperidone Sustained Release 30 mg',
    category: 'Anti-infective',
    therapeuticSegment: 'Gastrointestinal',
    dosageForm: 'Capsule',
    packSize: 'Strip of 10',
    description: 'Dual action gastric protection with proton pump inhibitor and prokinetic agent.',
    featured: true,
    active: true,
  },
  {
    id: 'vanzy-plus',
    name: 'VANZY PLUS',
    composition: 'Fungal Diastase + Papain + Vitamins + L-Lysine',
    category: 'Digestive Health',
    therapeuticSegment: 'Digestive Enzyme',
    dosageForm: 'Tablet',
    packSize: 'Strip of 15',
    description: 'Comprehensive digestive support with natural enzymes and amino acids.',
    featured: false,
    active: true,
  },
  {
    id: 'varoxim-200',
    name: 'VAROXIM 200',
    composition: 'Cefixime 200 mg',
    category: 'Anti-infective',
    therapeuticSegment: 'Antibiotic',
    dosageForm: 'Tablet',
    packSize: 'Strip of 10',
    description: 'Third generation cephalosporin for broad-spectrum antimicrobial coverage.',
    featured: false,
    active: true,
  },
  {
    id: 'vardec',
    name: 'VARDEC',
    composition: 'Nandrolone Decanoate',
    category: 'Prescription / Specialty Products',
    therapeuticSegment: 'Specialty Injectable',
    dosageForm: 'Injection',
    strength: '50 mg/ml or 100 mg/ml',
    packSize: 'Vial of 1 ml',
    description: 'Prescription medication. Use only under the supervision of a qualified healthcare professional.',
    featured: false,
    active: true,
  },
  {
    id: 'varnac',
    name: 'VARNAC',
    composition: 'Diclofenac Sodium 75 mg',
    category: 'Pain Management',
    therapeuticSegment: 'Anti-inflammatory',
    dosageForm: 'Injection',
    packSize: 'Ampoule of 3 ml',
    description: 'Potent NSAID for acute pain and inflammation management.',
    featured: false,
    active: true,
  },
  {
    id: 'varnim-p',
    name: 'VARNIM-P',
    composition: 'Nimesulide 100 mg + Paracetamol 325 mg',
    category: 'Pain Management',
    therapeuticSegment: 'Anti-inflammatory',
    dosageForm: 'Tablet',
    packSize: 'Strip of 10',
    description: 'Selective COX-2 inhibitor combined with paracetamol for effective analgesia.',
    featured: false,
    active: true,
  },
  {
    id: 'varocof',
    name: 'VAROCOF',
    composition: 'Dextromethorphan 10 mg + Phenylephrine HCl 5 mg + Chlorpheniramine Maleate 2 mg',
    category: 'Cough & Cold',
    therapeuticSegment: 'Cough & Cold',
    dosageForm: 'Syrup',
    packSize: '100 ml bottle',
    description: 'Triple action cough and cold formulation with cough suppressant, decongestant and antihistamine.',
    featured: false,
    active: true,
  },
  {
    id: 'varoflox-200',
    name: 'VAROFLOX 200',
    composition: 'Ofloxacin 200 mg',
    category: 'Anti-infective',
    therapeuticSegment: 'Antibiotic',
    dosageForm: 'Tablet',
    packSize: 'Strip of 10',
    description: 'Fluoroquinolone antibiotic for broad-spectrum bacterial infections.',
    featured: false,
    active: true,
  },
  {
    id: 'varoflox-oz',
    name: 'VAROFLOX-OZ',
    composition: 'Ofloxacin + Ornidazole',
    category: 'Anti-infective',
    therapeuticSegment: 'Antibiotic',
    dosageForm: 'Tablet',
    packSize: 'Strip of 10',
    description: 'Combination antibiotic for mixed bacterial and protozoal infections.',
    featured: false,
    active: true,
  },
  {
    id: 'vansocort',
    name: 'VANSOCORT',
    composition: 'Deflazacort 6 mg / 30 mg',
    category: 'Prescription / Specialty Products',
    therapeuticSegment: 'Corticosteroid',
    dosageForm: 'Tablet',
    packSize: 'Strip of 10',
    description: 'Prescription medication. Use only under the supervision of a qualified healthcare professional.',
    featured: false,
    active: true,
  },
  {
    id: 'varocet',
    name: 'VAROCET',
    composition: 'Levocetirizine 5 mg',
    category: 'Anti-allergic',
    therapeuticSegment: 'Antihistamine',
    dosageForm: 'Tablet',
    packSize: 'Strip of 10',
    description: 'Selective H1-receptor antagonist for rapid allergy symptom relief.',
    featured: false,
    active: true,
  },
  {
    id: 'varocef',
    name: 'VAROCEF',
    composition: 'Cefpodoxime 50 mg / 100 mg Dry Syrup',
    category: 'Anti-infective',
    therapeuticSegment: 'Pediatric Antibiotic',
    dosageForm: 'Dry Syrup',
    packSize: '30 ml bottle',
    description: 'Third generation cephalosporin in pediatric-friendly dry syrup formulation.',
    featured: false,
    active: true,
  },
];